Parameters:
  EnvironmentType: 
    Description: Environment Type
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Test
      - Production

Mappings:
  EnvironmentToInstanceType: # Map Name
    Dev: # Top level key
      Type: t3.micro # Second level key
    Test:
      Type: t3.nano
    Production: 
      Type: t3.small

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-79fd7eee"

      # Use the intrinsic function FindInMap to lookup the 
      # InstanceType value from the EnvironmentToInstanceTypeMap.
      # It references the EnvironmentType parameter provided to the template
      InstanceType: !FindInMap
        - EnvironmentToInstanceType # Map Name
        - !Ref EnvironmentType # Top Level Key
        - Type # Second Level Key

