Parameters:
  EnvironmentType: 
    Description: Environment Type
    Type: String
    Default: Dev
    AllowedValues:
      - "Dev"
      - "Test"
      - "Production"

  AmiID:
    Type: AWS::EC2::Image::Id
    Description: 'Amazon Machine Image ID'

Mappings:
  EnvironmentToInstanceType: 
    Dev: 
      InstanceType: "t3.micro"
    Test:
      InstanceType: "t3.nano"
    Production: 
      InstanceType: "t3.small"

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref AmiID
      InstanceType: !FindInMap
        - EnvironmentToInstanceType
        - !Ref EnvironmentType
        - "InstanceType"