AWSTemplateFormatVersion: '2010-09-09'

Description: 'Amazon EC2 - Workshop template.'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Amazon EC2 Configuration'
        Parameters:
          - AmiID

    ParameterLabels:
      AmiID:
        default: 'Amazon Machine Image ID'

Parameters:
  AmiID:
    Type: AWS::EC2::Image::Id
    Description: 'The ID of the AMI.'

  EnvType:
    Description: Environment type.
    Default: test
    Type: String
    AllowedValues:
      - prod
      - test
    ConstraintDescription: 'Must specify prod or test.'

Mappings:
  Environment:
    InstanceType:
      prod: m4.large
      test: t2.micro

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AmiID
      InstanceType: !FindInMap [Environment, InstanceType, !Ref EnvType]
      Tags:
        - Key: Name
          Value: !Join [ ' ', [ !Ref EnvType, Web Server ] ]

# Add your code here!